### PR TITLE
Quiz

### PR DESCRIPTION
**Pull request by lathammatt**

### CODE REVIEW

**Comment by morecallan** [comment]
This was so beautiful that it took us 17 days to marvel at. (But for realsies, don't hesitate to nudge the instructors when your review is no longer timely).

Excellent IIFE structure. Great modular code. Well named and concise functions. 

Before Merge:
- Make sure your textbox is bound 100% to the description. According to the instructions, it shouldn't just append it, but rather overwrite it.
- COMMENTS - for quizzes, it helps to use the quiz instructions as your guiding comments.

**Comment by lathammatt** [comment]
@morecallan Ehhhhhh, I did inquire with Joe about where he was with grading the quiz once a week. ;) But no worries. I know we're all busy.

Regarding the 100% text bound part, I had actually interpreted the instructions to be an edit feature to add on to the description since it did not specify overwriting. This was partly because of my previous job in Nissan warranty where it would be considered a tad illegal to go back and edit things like mileage. :P   And here I thought I left all that behind me.

**Comment by morecallan** [comment]
Totally get it. If you want this to be an 'edit' like function, then you need to have the current description value added to the text box on focus. Gotta stick with what the product owner wants, no matter how crazy (or stupid) it might be.

**Comment by lathammatt** [comment]
@morecallan Sigh. Darn product owners. :P  

I adjusted my javascript to clear the description when card is selected and the text becomes 100% bound to user input.

**Comment by morecallan** [comment]
👍 Beautiful!

**Pull request merged**
